FROM joyzoursky/python-chromedriver:3.8-alpine3.10-selenium as base

FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY requirements/test.txt /install/requirements.txt

RUN apk add --update \
        g++ \
        libxml2 \
        libxml2-dev &&\
    apk add libxslt-dev
RUN pip install --prefix=/install -r /install/requirements.txt

FROM base

ENV INSTALL_PATH /sunsetter
RUN mkdir ${INSTALL_PATH}
WORKDIR ${INSTALL_PATH}

ARG GIT_COMMIT_SHA1_BUILD
ENV GIT_COMMIT_SHA1=${GIT_COMMIT_SHA1_BUILD}

ENV FLASK_RUN_PORT=8000
EXPOSE ${FLASK_RUN_PORT}

ENV FLASK_ENV=development

COPY --from=builder /install /usr/local

COPY . .

ENTRYPOINT [ "flask", "run", "--cert=localhost.pem", "--key=localhost-key.pem", "--host=0.0.0.0" ]
