name = "sunsetter"
main = "worker/main.py"
compatibility_date = "2026-07-20"
compatibility_flags = ["python_workers"]

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[observability]
enabled = true
