name: Build and Deploy to Google Cloud Run

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - id: get_version
        uses: battila7/get-version-action@v2
        
      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
          
      - name: Configure docker
        run: gcloud auth configure-docker
        
      - name: Build and Push the Docker image
        run: |
          docker build . --build-arg $GITHUB_SHA --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${{ steps.get_version.outputs.version }}
          docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${{ steps.get_version.outputs.version }}
          
      - name: Push static files to Firebase hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT }}
          
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${{ steps.get_version.outputs.version }}
          service: ${{ secrets.GCLOUD_APP_NAME }}
          region: ${{ secrets.GCLOUD_REGION }}
          
      - name: Notify Sentry of deployment
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
